name: config 接口

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout iptv
        uses: actions/checkout@v5
        with:
          repository: zhoujck/iptv
          path: iptv

      - name: Delete workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: tools
        working-directory: tools
        run: |
          pwd
          pip install demjson3 requests==2.31.0
          python config.py
          cp -pdr ./output/xiaomi.txt ../jar/xiaomi.txt
          cp -pdr ./output/feimao.txt ../jar/feimao.txt
          python combine.py
          python combineF.py
          mkdir -p ext
          cp -p iptv/live.txt ext/live.txt
          rm -rf iptv
        shell: bash

      - name: 提交更改
        run: |
          git config user.email "zhoujck@live.com"
          git config user.name "zhoujck"
          git add .
          if ! git diff-index --quiet HEAD --; then
          git commit -m "更新JAR $(date +%Y%m%d%H%M)"
          git push -f origin main
          else
          echo "没有文件更新，不执行 git push"
          fi
