name: Local box 接口

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: tools
        run: |
          pwd 
          cd tools/
          pip install demjson3 requests==2.31.0
          python jar.py
          \cp -pdr Feimao.txt ../jar/Feimao.txt
          python combine.py
          \cp -pdr box_merged.json ../box_local.json
          rm -rf box_merged.json Feimao.txt
          cd ../
        shell: bash
        
      - name: 提交更改
        run: | 
          git config user.email "zhoujck@live.com"
          git config user.name "zhoujck" 
          git add .
          if ! git diff-index --quiet HEAD --; then
          git commit -m "更新JAR $(date +%Y%m%d%H%M)"
          git push -f origin main
          else
          echo "没有文件更新，不执行 git push"
          fi
     
